### ISSUE TITLE
Undying Crash with spikes?

### ISSUE THREAD

**Issue by iacuobos** [HyperPigeon/Eldritch-Mobs#102]
`java.lang.UnsupportedOperationException
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:50)
	at net.minecraft.class_1309.method_6012(class_1309.java:956)
	at net.hyper_pigeon.eldritch_mobs.ability.passive.defensive.UndyingAbility.onDamaged(UndyingAbility.java:41)
	at net.hyper_pigeon.eldritch_mobs.register.EldritchMobsEventListeners.lambda$init$1(EldritchMobsEventListeners.java:30)
	at net.hyper_pigeon.eldritch_mobs.ability.callback.onDamagedCallback.lambda$static$0(onDamagedCallback.java:13)
	at net.minecraft.class_1309.handler$hnd000$eldritch_mobs$applyOnDamageAbilities(class_1309.java:63187)
	at net.minecraft.class_1309.method_5643(class_1309.java:1246)
	at dev.hexnowloading.dungeonnowloading.block.SpikesBlock.method_9548(SpikesBlock.java:64)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:1121)
	at net.minecraft.class_1297.method_5852(class_1297.java:1137)
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1309.method_26318(class_1309.java:2312)
	at net.minecraft.class_1309.method_6091(class_1309.java:2232)
	at net.minecraft.class_1309.method_6007(class_1309.java:2719)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1548.method_5773(class_1548.java:161)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by HyperPigeon** [comment]
@majorsanty What version of the mod are you using?

**Comment by iacuobos** [comment]
Latest 
Disabling the trait fxed it
