### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FewerFlaws** [HyperPigeon/Eldritch-Mobs#19]
Just as I was loading up a world I got this crash.  Looks like it's related to Eldritch Mobs.
```
[23:32:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.getEntityName(ModifierComponent.java:177) ~[eldritch-mobs-1.6.5.jar:?]
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.get_mod_string(ModifierComponent.java:191) ~[eldritch-mobs-1.6.5.jar:?]
	at net.minecraft.class_1309.handler$zdh000$configureCustomNameANDremoveModifiersIfSpawnedInLampChunk(class_1309.java:3897) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:342) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1548.method_5773(class_1548.java:157) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-minecraft-1.16.5-client.jar:?]
	... 5 more
[23:32:56] [Server thread/ERROR]: This crash report has been saved to: E:\minecraft\multiMC\mmc-stable-win32\MultiMC\instances\5- Creatures\.minecraft\crash-reports\crash-2021-01-17_23.32.56-server.txt
[23:32:56] [Server thread/INFO]: Stopping server
[23:32:56] [Server thread/INFO]: Saving players
[23:32:56] [Server thread/INFO]: Saving worlds
[23:32:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[standardSave]'/minecraft:overworld
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 17/01/21 11:32 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.getEntityName(ModifierComponent.java:177)
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.get_mod_string(ModifierComponent.java:191)
	at net.minecraft.class_1309.handler$zdh000$configureCustomNameANDremoveModifiersIfSpawnedInLampChunk(class_1309.java:3897)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1548.method_5773(class_1548.java:157)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.getEntityName(ModifierComponent.java:177)
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.get_mod_string(ModifierComponent.java:191)
	at net.minecraft.class_1309.handler$zdh000$configureCustomNameANDremoveModifiersIfSpawnedInLampChunk(class_1309.java:3897)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1548.method_5773(class_1548.java:157)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 4
	Entity Name: Stormy Rust Creeper
	Entity's Exact location: 21.50, 17.00, -198.50
	Entity's Block location: World: (21,17,-199), Chunk: (at 5,1,9 in 1,-13; contains blocks 16,0,-208 to 31,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,-192), Chunk: (at 0,4,0 in 0,-12; contains blocks 0,0,-192 to 15,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 90657 game time, 8995 day time
	Level name: standardSave
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 626 (now: false), thunder time: 15637 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2790679464 bytes (2661 MB) / 4051697664 bytes (3864 MB) up to 4051697664 bytes (3864 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.3
		advdebug: Advancements Debug 2.2.0
		adventurez: AdventureZ 1.1.5
		amecs: Amecs 1.3.2+mc.1.16.3
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
		auto_third_person: Auto Third Person 1.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		backslot: BackSlot 1.1.8
		bedrockify: BedrockIfy 0.2.1
		bedrockwaters: BedrockWaters 1.4.3+1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		biomemakeover: Biome Makeover 1.16.4-1.2.7
		blame: Blame 1.16.4-2.4.0
		bloodparticles: Blood Particles 1.1.1
		blur: Blur (Fabric) 2.0.0
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.0+build.51
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crimsonmoon: Crimson Moon 1.2.3-1.16.2
		crowdin-translate: CrowdinTranslate 1.2
		customportalapi: customportalapi 0.0.1-beta18-1.16
		dark-loading-screen: Dark Loading Screen 1.6.1
		darkness: True Darkness 1.6.58
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.0
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		eldritch_mobs: Eldritch Mobs 1.6.5
		enchant_giver: Enchant Giver 1.0.2
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5ba7
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabrication: Fabrication 1.2.11
		fabricloader: Fabric Loader 0.11.1
		fabriczero: Fabric Zero 0.2.0
		fallingleaves: Falling Leaves 1.4
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.9
		firstperson: FirstpersonModel 2.0.0-SNAPSHOT
		ghastly_wail: Ghastly Wail 1.0.1+MC1.16.2-1.16.5
		giantai: GiantAI 1.0.3
		herdspanic: Herds Panic 1.0.0
		horsestatsvanilla: Horse Stats Vanilla 4.1.4
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		ice_boat_nerf: Ice Boat Nerf 1.0.4+MC1.16.2-1.16.5
		inventoryhotswap: Inventory Hotswap 1.0
		itemmodelfix: Item Model Fix 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jukefix: JukeFix 1.0.0
		kirin: Kirin UI 1.7-1.16.2
		lambdynlights: LambDynamicLights 1.3.3+1.16
		lazydfu: LazyDFU 0.1.1
		libgui: LibGui 3.0.0+1.16.3
		libstructure: LibStructure 1.5
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.14.13+build.19
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mousewheelie: Mouse Wheelie 1.6.2+mc1.16.4
		mythicmetals: Mythic Metals 0.9.9-snapshot-D
		noanglebrackets: NoAngleBrackets 1.0.1
		notenoughanimations: NotEnoughAnimations 1.0.3
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		overworld_two: Overworld 2 1.0.4
		phosphor: Phosphor 0.7.0+build.10
		presencefootsteps: Presence Footsteps r29+1.16.4
		randompatches: RandomPatches 2.1.9-fabric
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		roughlyenoughitems: Roughly Enough Items 5.8.9
		roughlyenoughitems-api: REI (API) 5.8.9
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.9
		roughlyenoughitems-runtime: REI (Runtime) 5.8.9
		satin: Satin 1.5.1
		sep: Status Effects+ 1.16.2_7
		skinswapper: Minecraft Skin Change Mod 2.0.1
		sodium: Sodium 0.1.0
		spark: spark 1.4.3
		spruceui: SpruceUI 2.0.1+1.16
		starry_sky: Starry Sky 1.0.4-1.16.4
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		traverse: Traverse 3.1.0+build.15
		tweed: Tweed API 3.0.0-beta.22
		unearthed: Unearthed 1.0.5
		unsaddlepigs: Unsaddle Pigs 1.0.1-mc1.16.4-fabric
		villagernames: Villager Names 1.6.0
		voyager: Voyager 1.0.0
		zoob: Monster Of The Ocean Depths 2.5.0
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, file/mod_trimming, file/mod_adjustment
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# E:\minecraft\multiMC\mmc-stable-win32\MultiMC\instances\5- Creatures\.minecraft\crash-reports\crash-2021-01-17_23.32.56-server.txt
Exception in thread "Async Class PreLoader" AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by FewerFlaws** [comment]
This world continued to crash on startup until I disabled eldritch mobs.

**Comment by FewerFlaws** [comment]
Oh, this could easily be related to the blacklist.  The report says it was a stormy rust creeper.  I have creepers on the blacklist.

**Comment by HyperPigeon** [comment]
Fixed (hopefully) in the latest version. Please let me know if the problem still persists.
