### ISSUE TITLE
Ticking entity crash (latest version)

### ISSUE THREAD

**Issue by Chuunkyz** [HyperPigeon/Eldritch-Mobs#33]
Description: Ticking entity

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1657.method_7290(boolean)'
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.SnatcherComponent.useAbility(SnatcherComponent.java:33)
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.useAbility(ModifierComponent.java:275)
	at net.hyper_pigeon.eldritch_mobs.EldritchMobsMod.useAbility(EldritchMobsMod.java:65)
	at net.minecraft.class_1308.handler$cbi000$ability_try(class_1308.java:3309)
	at net.minecraft.class_1308.method_5773(class_1308.java)
	at net.minecraft.class_1642.method_5773(class_1642.java:233)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by HyperPigeon** [comment]
I was unable to replicate the crash. Is it possible for you to describe the context under which it occured?

**Comment by SgtSavvy** [comment]
It’s the same issue that’s plaguing my server as well. Snatcher mobs are causing client side crashes left and right. The latest update did not stop this from happening.

**Comment by HyperPigeon** [comment]
I've removed snatcher in the latest release. Please let me know if the issue still persists.

**Comment by milkev** [comment]
Proud to announce that the snatcher ability has borked my game as well. I dont care for the ability, and have just disabled it. heres my mod list though if anyone else cares to try and figure it out.
[https://pastebin.com/jaR6gL0Q](https://pastebin.com/jaR6gL0Q)

**Comment by HyperPigeon** [comment]
Snatcher has been COMPLETELY removed from the mod as of the latest release. The 1.17 update completely broke the ability, and it was known to be a problem child before then so I made the decision to just can it.
