### ISSUE TITLE
ingame crash when rendering some entities

### ISSUE THREAD

**Issue by Chuunkyz** [HyperPigeon/Eldritch-Mobs#40]
i think i already reported that, but this is still a thing in the lates version :

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
 
Time: 11/14/21, 12:08 PM
Description: Rendering entity in world
 
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.minecraft.class_1799.method_7909()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.handler$cgm000$renderGlowingArmorMixin(ArmorFeatureRenderer:1047)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:35)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:22)
	at net.minecraft.client.render.entity.LivingEntityRenderer.redirect$bfd000$featureRendererTransformer(LivingEntityRenderer:1534)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:139)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:45)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:18)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1482)
	at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:525)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:507)
	at net.minecraft.client.render.WorldRenderer.handler$bdb000$iris$renderTerrainShadows(WorldRenderer:4338)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1160)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_970.handler$cgm000$renderGlowingArmorMixin(class_970.java:1047)
	at net.minecraft.class_970.method_17157(class_970.java:35)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.redirect$bfd000$featureRendererTransformer(class_922.java:1534)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
Mixins in Stacktrace:
	net.minecraft.class_970:
		me.shedaniel.cloth.mixin.armor.MixinArmorFeatureRenderer (cloth-armor-api-v1.mixins.json)
		net.adventurez.mixin.client.ArmorFeatureRendererMixin (adventurez.mixins.json)
		shadow.fabric.mixin.client.rendering.MixinArmorFeatureRenderer (betterend.mixins.shadow.json)
		software.bernie.geckolib3.mixins.fabric.MixinArmorFeatureRenderer (fabric.mixins.json)
		ru.pinkgoosik.villagerhats.mixin.ArmorFeatureRendererMixin (villagershats.mixins.json)
		io.github.kosmx.emotes.fabric.mixin.ArmorFeatureRendererMixin (emotecraft.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.MixinArmorFeatureRenderer (fabric-rendering-v1.mixins.json)
		io.github.apace100.cosmetic_armor.mixin.MixinCosmeticArmorVisibility (cosmetic-armor.mixins.json)
		raltsmc.desolation.mixin.client.render.entity.feature.ArmorFeatureRendererMixin (desolation.mixins.json)
		svenhjol.charm.mixin.colored_glints.GetArmorStackMixin (charm.mixins.json)
		artifality.mixin.client.ArmorFeatureRendererMixin (artifality.mixins.json)
		svenhjol.charm.mixin.armor_invisibility.PreventArmorRenderMixin (charm.mixins.json)
	net.minecraft.class_922:
		net.fabricmc.fabric.mixin.client.rendering.LivingEntityRendererAccessor (fabric-rendering-v1.mixins.json)
		io.github.kosmx.emotes.fabric.mixin.LivingEntityRenderRedirect (emotecraft.mixins.json)
		com.github.platymemo.alaskanativecraft.mixin.client.LivingEntityRendererMixin (alaskanativecraft.mixins.json)
		svenhjol.charm.mixin.accessor.LivingEntityRendererAccessor (charm.mixins.json)
		io.github.lucaargolo.terrarianslimes.mixin.LivingEntityRendererMixin (terrarianslimes.mixins.json)
		io.github.lucaargolo.kibe.mixin.LivingEntityRendererMixin (kibe.mixins.json)
		net.coderbot.iris.mixin.MixinLivingEntityRenderer (mixins.iris.json)
		artifacts.mixin.mixins.item.umbrella.client.LivingEntityRendererMixin (artifacts.mixins.json)
	net.minecraft.class_927:
		moriyashiine.bewitchment.mixin.client.MobEntityRendererMixin (bewitchment.mixins.json)
		virtuoel.pehkui.mixin.client.compat115plus.MobEntityRendererMixin (pehkui.mixins.json)
 
-- Entity being rendered --
Details:
	Entity Type: minecraft:zombie (net.minecraft.class_1642)
	Entity ID: 7124
	Entity Name: Zombie
	Entity's Exact location: 710.05, -2.03, -160.92
	Entity's Block location: World: (710,-3,-161), Section: (at 6,13,15 in 44,-1,-11; chunk contains blocks 704,-64,-176 to 719,319,-161), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: -0.11, -0.16, 0.08
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.23000000417232513d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"stepheightentityattribute:stepheight"},{Base:20.0d,Name:"minecraft:generic.max_health"}],Brain:{memories:{}},CanBreakDoors:0b,CanPickUpLoot:0b,DeathTime:0s,DrownedConversionTime:-1,FallDistance:0.0f,FallFlying:0b,Fire:0s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:20.0f,HurtByTimestamp:0,HurtTime:0s,InWaterTime:-1,Invulnerable:0b,IsBaby:1b,LeftHanded:0b,Motion:[-0.1065d,-0.155125d,0.081125d],OnGround:0b,OnSoulFire:0b,PersistenceRequired:0b,PortalCooldown:0,Pos:[710.0505647582212d,-2.0261333338419596d,-160.918930737468d],Rotation:[52.03125f,0.0f],UUID:[I;676045698,-305577945,-1142203071,1059508106],arcanus:{DiscombobulatedTimer:0,IsDiscombobulated:0b},cardinal_components:{"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0},"bewitchment:blood":{Blood:100},"bewitchment:curses":{Curses:[]},"bewitchment:fake_mob":{TargetUUID:""},"bewitchment:familiar":{Familiar:0b},"bewitchment:minion":{MasterUUID:""},"eldritch_mobs:eldritch_modifiers":{eldritch:0b,elite:0b,rank:1b,saved_mods:{},ultra:0b}},checkedIfInLampChunk:0b}
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:169)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:160)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1482)
	at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:525)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:507)
	at net.minecraft.client.render.WorldRenderer.handler$bdb000$iris$renderTerrainShadows(WorldRenderer:4338)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1160)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		fudge.notenoughcrashes.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
 
-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_3886@2d1fdb05
	Location: -27.23,-16.63,0.36 - World: (-28,-17,0), Section: (at 4,15,0 in -2,-2,0; chunk contains blocks -32,-64,0 to -17,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 51.30003
	Delta: 0.4800206
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		fudge.notenoughcrashes.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
 
-- Affected level --
Details:
	All players: 1 total; [class_746['moholmarn'/132, l='ClientLevel', x=737.37, y=13.00, z=-161.36]]
	Chunk stats: 1024, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (-220,87,-209), Section: (at 4,7,15 in -14,5,-14; chunk contains blocks -224,-64,-224 to -209,319,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 196742 game time, 12655 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

**Comment by HyperPigeon** [comment]
Do you have glowing enabled?

**Comment by HyperPigeon** [comment]
Hopefully, this has been fixed in the latest release. I believe the issue was caused by an incompatibility between 1.17 and 1.17.1. Open up the issue again if the problem persists.
