### ISSUE TITLE
Infrequent NoSuchMethodError

### ISSUE THREAD

**Issue by nephatrine** [HyperPigeon/Eldritch-Mobs#6]
I'm running MC 1.16.2 and eldritch-mobs-1.3.1 and things will seem to be running OK and I do get "eldritch" mobs spawning... but every once in a while I get a crash like this:

```
java.lang.NoSuchMethodError: net.minecraft.class_1299.method_5899(Lnet/minecraft/class_1937;Lnet/minecraft/class_2487;Lnet/minecraft/class_2561;Lnet/minecraft/class_1657;Lnet/minecraft/class_2338;Lnet/minecraft/class_3730;ZZ)Lnet/minecraft/class_1297;
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.DuplicatorComponent.useAbility(DuplicatorComponent.java:27)
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.useAbility(ModifierComponent.java:259)
	at net.hyper_pigeon.eldritch_mobs.EldritchMobsMod.useAbility(EldritchMobsMod.java:37)
	at net.minecraft.class_1308.handler$zfk000$ability_try(class_1308.java:1827)
	at net.minecraft.class_1308.method_5773(class_1308.java)
	at net.minecraft.class_3218.method_18762(class_3218.java:616)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:406)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)
```

Not really sure what is the cause. If there's more information you need, just let me know. I'm using fabric-api-0.18.0+build.397-1.16 and Cardinal-Components-API-2.5.0 if that matters.

**Comment by HyperPigeon** [comment]
Eldritch Mobs has not been updated to 1.16.2 yet, this is most likely the cause of the crash.

**Comment by nephatrine** [comment]
Ah okay you're probably right. I disabled the Duplicator in the config and haven't had any crashes since. It does seem to generally work thankfully, though I haven't verified every single feature actually functions as expected. Sorry for opening on an unsupported version!
