### ISSUE TITLE
Server crashs when a player join in.

### ISSUE THREAD

**Issue by Touch-Night** [HyperPigeon/Eldritch-Mobs#70]
[21:00:26] [] [Quilt Loader/GameProvider]:Loading Minecraft 1.19.2 with Quilt Loader 0.17.5-beta.2
[21:00:29] [main]:Loading Minecraft 1.19.2 with Quilt Loader 0.17.5-beta.2
[21:03:29] [Server thread/ERROR]:Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
at net.minecraft.se
MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.hyper_pigeon.eldritch_mobs.ability.Ability.passiveApply(net.minecraft.class_1308)" because "ability" is null
at net.hyper_pigeon.eldritch_mobs.register.EldritchMobsEventListeners.lambda$init$3(EldritchMobsEventListeners.java:53) ~[eldritch-mobs-1.12.7.jar:?]
at net.hyper_pigeon.eldritch_mobs.ability.callback.passiveApplyCallback.lambda$static$0(passiveApplyCallback.java:13) ~[eldritch-mobs-1.12.7.jar:?]
at net.minecraft.class_1309.handler$zig000$applyPassiveAbilities(class_1309.java:6676) ~[server-intermediary.jar:?]
at net.minecraft.class_1309.method_5773(class_1309.java:2465) ~[server-intermediary.jar:?]
at net.minecraft.class_1308.method_5773(class_1308.java:353) ~[server-intermediary.jar:?]
at net.minecraft.class_1642.method_5773(class_1642.java:233) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.redirect$zod000$servercore$shouldTickEntity(class_3218.java:5245) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[server-intermediary.jar:?]
at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
... 5 more

My server installed eldritchmobs 1.12.6 before.
I changed all the names in mod configs (eldritch_mobs.json5) like this: 
"alchemistConfig": {
		"name": "炼金术士",
		"disabled": false,
		"cooldown": 200,
		"useStrongHealing": false,
		"useStrongHarming": false
	},

while using the edited configs, 1.12.6 also cause the server to crash.

**Comment by Touch-Night** [comment]
It's like the edited config file causing the server to crash.
