### ISSUE TITLE
Need explanation of each ability

### ISSUE THREAD

**Issue by qsefthuopq** [HyperPigeon/Eldritch-Mobs#8]
I'm working on translating this mod,but there is no command for summoning a mob with one specific ability.
So I need explanation of each ability.
Could you also make the mob name translatable?

**Comment by qsefthuopq** [comment]
Game crashed when I summon a neutral creature：
`-- Head --
Thread: Server thread
Stacktrace:
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.getEntityName(ModifierComponent.java:183)
	at net.hyper_pigeon.eldritch_mobs.mod_components.modifiers.ModifierComponent.get_mod_string(ModifierComponent.java:197)
	at net.minecraft.class_1309.handler$zcl000$configureCustomName(class_1309.java:3876)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:616)

-- Entity being ticked --
Details:
	Entity Type: minecraft:sheep (net.minecraft.class_1472)
	Entity ID: 446
	Entity Name: Sheep
	Entity's Exact location: 35.52, 80.00, -69.83
	Entity's Block location: World: (35,80,-70), Chunk: (at 3,5,10 in 2,-5; contains blocks 32,0,-80 to 47,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:406)

-- Affected level --
Details:
	All players: 1 total; [class_3222['rewriter'/159, l='ServerLevel[新的世界]', x=35.52, y=80.00, z=-69.83]]
	Chunk stats: ServerChunkCache: 2344
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,75,-64), Chunk: (at 0,4,0 in 6,-4; contains blocks 96,0,-64 to 111,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 369877 game time, 1000 day time
	Level name: 新的世界
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 167492 (now: false), thunder time: 3042 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)`

**Comment by HyperPigeon** [comment]
In regards to the crash, the game crashes when you try to summon a passive mob (such as a sheep) as a "special" mob since only neutral and hostile mobs (such as golems, spiders, zombies, skeletons, enderman, etc) can become "special" mobs.
